frappe_x1_04e961e9:
    data_format: csv
    data_root: C:\Users\azsar\Frappe_x1\
    feature_cols:
    -   active: true
        dtype: float
        name: [user, item, daytime, weekday, isweekend, homework, cost, weather, country,
            city]
        type: categorical
    label_col: {dtype: float, name: label}
    min_categr_count: 1
    test_data: C:\Users\azsar\Frappe_x1\test.csv
    train_data: C:\Users\azsar\Frappe_x1\train.csv
    valid_data: C:\Users\azsar\Frappe_x1\valid.csv