Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

AFN_test:
    model: AFN
    dataset_id: frappe_x1_04e961e9
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 0.001
    embedding_regularizer: 0.1
    net_regularizer: 0
    batch_size: 2048
    embedding_dim: 10
    logarithmic_neurons: 1000
    afn_hidden_units: [400]
    afn_activations: relu
    afn_dropout: 0.4
    ensemble_dnn: True
    dnn_hidden_units: [400, 400, 400]
    dnn_activations: relu
    dnn_dropout: 0.2
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: 'AUC'
    monitor_mode: 'max'

AFN_default: # This is a config template
    model: AFN
    dataset_id: TBD
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 20
    logarithmic_neurons: 1200
    afn_hidden_units: [400, 400, 400]
    afn_activations: relu
    afn_dropout: 0
    ensemble_dnn: False
    dnn_hidden_units: [400, 400, 400]
    dnn_activations: relu
    dnn_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

