Base:
    model_root: './checkpoints/'
    num_workers: 1
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

NFM_test:
    model: NFM
    dataset_id: frappe_x1_04e961e9
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 0.001 
    embedding_regularizer: 0.01
    net_regularizer: 0
    batch_size: 512
    embedding_dim: 10
    hidden_units: [400, 400, 400]
    hidden_activations: relu
    net_dropout: 0.1
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: 'AUC'
    monitor_mode: 'max'

NFM_default: # This is a config template
    model: NFM
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 40
    hidden_units: [500, 500, 500]
    hidden_activations: relu
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
